### PR TITLE
fix error with description

### LINKED ISSUE #50: repositories with no description cause an error
Repositories that don't have a description cause the following error:

```bash
Traceback (most recent call last):
  File "/action/workspace/crawler.py", line 84, in <module>
    innersource_repo["score"] = repo_activity.score.calculate(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.[11](https://github.com/innersource-portal-demo/project-portal-for-innersource/actions/runs/6279610170/job/17055587875#step:4:12)/site-packages/repo_activity/score.py", line 54, in calculate
    len(repo["description"]) > 30
    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

A workaround is to add a description but it would be better if the crawler could handle repositories without descriptions gracefully and continue running.

### PR DESCRIPTION
**Pull request by issamansur**
fix #50 
Changes:
- add field/key `description` for repositories with empty description
- add type for variable `innersource_repo`

### CODE REVIEW

**Comment by zkoppert** [comment]
Thanks for working on this! A couple of issues I ran into when testing this:

```bash
Traceback (most recent call last):
  File "/Users/zkoppert/repos/innersource-crawler/./crawler.py", line 84, in <module>
    innersource_repo.set_default('description', '')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'set_default'. Did you mean: 'setdefault'?
```

and so I changed `set_default` to `setdefault` and ran again. At that point I am still receiving the following:

```bash
Traceback (most recent call last):
  File "/Users/zkoppert/repos/innersource-crawler/./crawler.py", line 87, in <module>
    innersource_repo["score"] = repo_activity.score.calculate(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/repo_activity/score.py", line 54, in calculate
    len(repo["description"]) > 30
    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

Reading that error more carefully than I did before, I see that this is actually a failure in the dependency (repo_activity_score) The line the error references is here: https://github.com/InnerSourceCommons/repo-activity-score/blob/main/src/repo_activity/score.py#L54 and I believe that should be changed to see if repo["description"] = "" or something like that. 

Would you like to make that change on that repo or would you prefer I did that? @issamansur

**Comment by issamansur** [comment]
I saw that problem in dependency, but I thought that simple method `set_default` from class `dict` must to solve this problem elegantly. But I do mistake(
I can try to change this, but u are leader there)

**Comment by issamansur** [comment]
Done! Try to test this

**Comment by zkoppert** [comment]
That worked!!! Thank you for working that out! 🎉

**Pull request merged**
